### ISSUE TITLE
Practical checklist for deploying page embeds

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud-pages#16]
This will probably become a tracking ticket, as some of these will require their own robust discussions on their own tickets.
- [x] Mock up pre-progressive-enhancement markup (effectively noscript)
- [x] Mock up post-enhancement direct embed code
- [x] Implement mockups
- [x] Final dev pieces
  - [x] Let options be set
  - [x] Adorn contributor/org names with links to public search
  - [x] Invert `DC-embed-stub/DC-embed` semantics
  - [x] Add page embed composition to wizard
  - [x] Add page embed links around workspace
  - [x] Bundle the page embed JS into the platform and deploy to CDN
  - [x] Update generated embed code to reference proper JS
  - [x] Add translation support (will be just English for now) and ping translators
  - [x] Replace visual selector with drop-down
  - [x] Add live preview
  - [x] Add "coming soon: wordpress shortcode"
  - [x] Pixel ping
- [x] Documentation
  - [x] Push app to staging; get screen grab of menu.
  - [x] Write English and Spanish help section at /help/publishing#embed-page
  - [x] Merge docs-page-embed branch with master
- [x] Marketing/communication
  - [x] Write newsletter text
  - [x] Write blog post
  - [x] Upon deployment, publish blog post, send newsletter and tweet 

<hr>

- [x] CDN
- [x] Fallback for old browsers (#12)
- Add note count to page selector on wizard (https://github.com/documentcloud/documentcloud/issues/300)
- Create page endpoint for displaying single pages as a resource and **provide oEmbed endpoint** (#26)
- iframes (#18)

**Comment by reefdog** [comment]
"Mock up" meaning write the embed codes we want to be issuing, and then make them work.

**Comment by knowtheory** [comment]
:+1: agreed on where the line is drawn for MVP!

ROCK IT :rocket:

**Comment by reefdog** [comment]
Cool!

**Comment by anthonydb** [comment]
Added documentation and communications tasks to the checklist.

**Comment by reefdog** [comment]
@anthonydb Might be a good idea to merge `docs-page-embed` into `page-embed` (which I published last night) so we can have it all in one place before going to master.

**Comment by knowtheory** [comment]
Yes, please do that :) :+1:

**Comment by anthonydb** [comment]
Updated the checklist to note that page embed links in the workspace need to be supported in the multiple workspace languages we support.

**Comment by reefdog** [comment]
As in will need string translations? Yupppp. I have `[need2i18n]` sprinkled everywhere so I can quickly find places that need it.

**Comment by reefdog** [comment]
Tomorrow's tasks (putting here for myself):

[ ] Bundle the page embed JS into the platform and deploy to CDN
[ ] Update generated embed code to reference proper JS
[ ] Add translation support (will be just English for now) and ping translators
[ ] Begin live embed preview

**Comment by reefdog** [comment]
- [ ] Add note count to page selector on wizard
